cf21:
  marker: "default_single_marker"
  dynamics: "default"
  big_quad: False
  battery:
    voltage_warning: 3.8  # V
    voltage_critical: 3.7 # V
  firmware_params:
    kalman:
      pNAcc_xy: 1.0 # default 0.5
      pNAcc_z: 2.0 # default 1.0
      mNGyro_rollpitch: 0.1 # default 0.1
      mNGyro_yaw: 0.1 # default 0.1
    ctrlMel:
      kp_xy: 0.4 #0.6 # p for position
      kd_xy: 0.2 # 0.35 # d for position
      ki_xy: 0.05
      i_range_xy: 2.0
      kR_xy: 70000 # p for attitude
      kw_xy: 20000 # d for attitude
      kR_z: 60000 # 70000 # p for yaw
      kw_z: 12000 # 30000  # d for yaw
      ki_m_z: 500 #0 #20000     # i for yaw
      i_range_m_z: 1500 # i range for yaw
      kd_omega_rp: 200 # roll and pitch angular velocity d gain
      kp_z: 1.25
      kd_z: 0.4
      ki_z: 0.05
      i_range_z: 0.4
      mass: 0.032
      massThrust: 132000
    pwm:
      d00: 0.5009717811726693
      d10: 0.11823595371065385
      d01: -0.41225540923278853
      d20: -0.002065562409668875
      d11: -0.04287969844506664

      e00: -9.855774395877377
      e10: 3.0164756915292554
      e01: 26.716368783384496

      new_thrust_comp: 1
    sysId:
      thrust_to_torque: 0.006
      arm_length: 0.046
    ctrlSJC:
      mass: 0.034
      # attitude lambda
      Katt_Px: 10
      Katt_Py: 10
      Katt_Pz: 4
      # attitude K
      Katt_Dx: 0.002 # 0.0012
      Katt_Dy: 0.002 # 0.0012
      Katt_Dz: 0.001 # 0.0012

      Katt_Dwx: 0.00008
      Katt_Dwy: 0.00008
      Katt_Dwz: 0.00002

      Katt_Ix: 0.002 # 0.001 
      Katt_Iy: 0.002 # 0.001 
      Katt_Iz: 0.004 # 0.0005 # 0.0005
      Katt_I_limit: 2 # 20

      Jtune_x: 16e-6
      Jtune_y: 16e-6
      Jtune_z: 30e-6

      Kpos_Px: 20 # 15 # 15 # 12
      Kpos_Py: 20 # 15 # 15 # 12
      Kpos_Pz: 10 # 12 # 12 # 12
      Kpos_P_limit: 100.0
      Kpos_Dx: 10 # 10 # 8
      Kpos_Dy: 10 # 10 # 8
      Kpos_Dz: 5 # 8 # 8
      Kpos_D_limit: 100.0
      Kpos_Ix: 3 #5
      Kpos_Iy: 3 #5
      Kpos_Iz: 10 #20
      Kpos_I_limit: 0.1
      Kpos_I_decay: 1.0 #0.997 # 0.75 ** 0.01
    # ctrlSJC2:
    #   T_d_lambda: 10
    #   T_d_dot_limit: 1
    #   Katt_Dw_limit: 10000


# crazyflieTypes:
#   default:
#     bigQuad: False
#     batteryVoltageWarning: 3.8  # V
#     batteryVoltateCritical: 3.7 # V
#     markerConfiguration: 0 # change to 3 for single marker tracking
#     dynamicsConfiguration: 0
#     firmwareParams:
#       ctrlMel:
#         kp_xy: 0.4 #0.6 # p for position
#         kd_xy: 0.2 # 0.35 # d for position
#         ki_xy: 0.05
#         i_range_xy: 2.0
#         kR_xy: 70000 # p for attitude
#         kw_xy: 20000 # d for attitude
#         kR_z: 60000 # 70000 # p for yaw
#         kw_z: 12000 # 30000  # d for yaw
#         ki_m_z: 500 #0 #20000     # i for yaw
#         i_range_m_z: 1500 # i range for yaw
#         kd_omega_rp: 200 # roll and pitch angular velocity d gain
#         kp_z: 1.25
#         kd_z: 0.4
#         ki_z: 0.05
#         i_range_z: 0.4
#         mass: 0.032
#         massThrust: 132000
#   defaultSingleMarker:
#     bigQuad: False
#     batteryVoltageWarning: 3.8  # V
#     batteryVoltateCritical: 3.7 # V
#     markerConfiguration: 3 # changed to 3 for single marker tracking
#     dynamicsConfiguration: 0
#     firmwareParams:
#       kalman:
#         pNAcc_xy: 4.0 # default 0.5
#         pNAcc_z: 8.0 # default 1.0
#         mNGyro_rollpitch: 0.2 # default 0.1
#         mNGyro_yaw: 0.1 # default 0.1
#       ctrlMel:
#         kp_xy: 0.4 #0.6 # p for position
#         kd_xy: 0.2 # 0.35 # d for position
#         ki_xy: 0.05
#         i_range_xy: 2.0
#         kR_xy: 70000 # p for attitude
#         kw_xy: 20000 # d for attitude
#         kR_z: 60000 # 70000 # p for yaw
#         kw_z: 12000 # 30000  # d for yaw
#         ki_m_z: 500 #0 #20000     # i for yaw
#         i_range_m_z: 1500 # i range for yaw
#         kd_omega_rp: 200 # roll and pitch angular velocity d gain
#         kp_z: 1.25
#         kd_z: 0.4
#         ki_z: 0.05
#         i_range_z: 0.4
#         mass: 0.032
#         massThrust: 132000
#   CF21SingleMarker:
#     bigQuad: False
#     batteryVoltageWarning: 3.8  # V
#     batteryVoltateCritical: 3.7 # V
#     markerConfiguration: 3 # changed to 3 for single marker tracking
#     dynamicsConfiguration: 0
#     firmwareParams:
#       kalman:
#         pNAcc_xy: 1.0 # default 0.5
#         pNAcc_z: 2.0 # default 1.0
#         mNGyro_rollpitch: 0.1 # default 0.1
#         mNGyro_yaw: 0.1 # default 0.1
#       ctrlMel:
#         kp_xy: 0.4 #0.6 # p for position
#         kd_xy: 0.2 # 0.35 # d for position
#         ki_xy: 0.05
#         i_range_xy: 2.0
#         kR_xy: 70000 # p for attitude
#         kw_xy: 20000 # d for attitude
#         kR_z: 60000 # 70000 # p for yaw
#         kw_z: 12000 # 30000  # d for yaw
#         ki_m_z: 500 #0 #20000     # i for yaw
#         i_range_m_z: 1500 # i range for yaw
#         kd_omega_rp: 200 # roll and pitch angular velocity d gain
#         kp_z: 1.25
#         kd_z: 0.4
#         ki_z: 0.05
#         i_range_z: 0.4
#         mass: 0.032
#         massThrust: 132000
#   medium:
#     bigQuad: True
#     batteryVoltageWarning: 7.6  # V
#     batteryVoltateCritical: 7.4 # V
#     markerConfiguration: 1
#     dynamicsConfiguration: 0
#     firmwareParams:
#       ctrlMel:
#         kp_xy: 2.0 # p for position
#         kd_xy: 1.0 # d for position
#         ki_xy: 0.1 # i for position
#         i_range_xy: 2.0 # range for position
#         kR_xy: 50000 # 50000 # p for attitude
#         kw_xy: 16000 # 16000 # d for attitude
#         kR_z: 60000 # p for yaw
#         kw_z: 12000 # d for yaw
#         ki_m_z: 500 # i for yaw
#         i_range_m_z: 1500 # i range for yaw
#         kd_omega_rp: 200 # roll and pitch angular velocity d gain
#         kp_z: 3 # 1.25
#         kd_z: 1.0
#         ki_z: 0.5 # 0.05
#         i_range_z: 2.0
#         mass: 0.110
#         massThrust: 23000 # 23000 - full battery
#   large:
#     bigQuad: True
#     batteryVoltageWarning: 11.4  # V
#     batteryVoltateCritical: 11.1 # V
#     markerConfiguration: 2
#     dynamicsConfiguration: 0
#     firmwareParams:
#       ctrlMel:
#         kp_xy: 8.0 # 0.4 #0.6 # p for position
#         kd_xy: 3.0 # 0.2 # 0.35 # d for position
#         ki_xy: 1.0 # 0.05
#         i_range_xy: 2.0
#         kR_xy: 30000 # 40000 # p for attitude
#         kw_xy: 9000 # 13000 # d for attitude
#         kR_z: 40000 # 70000 # p for yaw
#         kw_z: 10000 # 30000  # d for yaw
#         ki_m_z: 500 #0 #20000     # i for yaw
#         i_range_m_z: 1500 # i range for yaw
#         kd_omega_rp: 100 # roll and pitch angular velocity d gain
#         kp_z: 8.0 # 1.25
#         kd_z: 3.0 # 0.4
#         ki_z: 2.0 # 0.05
#         i_range_z: 4.0
#         mass: 0.380
#         massThrust: 5400 # 5500 - full battery
# numMarkerConfigurations: 4
# markerConfigurations:
#   "0":  # for standard Crazyflie
#     numPoints: 4
#     offset: [0.0, -0.01, -0.04]
#     points:
#       "0": [0.0177184,0.0139654,0.0557585]
#       "1": [-0.0262914,0.0509139,0.0402475]
#       "2": [-0.0328889,-0.02757,0.0390601]
#       "3": [0.0431307,-0.0331216,0.0388839]
#   "1": # medium frame
#     numPoints: 4
#     offset: [0.0, 0.0, -0.03]
#     points:
#       "0": [-0.00896228,-0.000716753,0.0716129]
#       "1": [-0.0156318,0.0997402,0.0508162]
#       "2": [0.0461693,-0.0881012,0.0380672]
#       "3": [-0.0789959,-0.0269793,0.0461144]
#   "2": # big frame
#     numPoints: 4
#     offset: [0.0, 0.0, -0.06]
#     points:
#       "0": [0.0558163,-0.00196302,0.0945539]
#       "1": [-0.0113941,0.00945842,0.0984811]
#       "2": [-0.0306277,0.0514879,0.0520456]
#       "3": [0.0535816,-0.0400775,0.0432799]
#   "3":  # for standard Crazyflie with a single marker
#     numPoints: 1
#     offset: [0.0, -0.01, -0.04]
#     points:
#       "0": [0.0177184,0.0139654,0.0557585]
# numDynamicsConfigurations: 1
# dynamicsConfigurations:
#   "0":
#     maxXVelocity: 2.0
#     maxYVelocity: 2.0
#     maxZVelocity: 3.0
#     maxPitchRate: 20.0
#     maxRollRate: 20.0
#     maxYawRate: 10.0
#     maxRoll: 1.4
#     maxPitch: 1.4
#     maxFitnessScore: 0.001

