name: ROS2 (Ubuntu)

on: [push, pull_request]

# Based on example provided at https://github.com/ros-tooling/setup-ros

jobs:
  # build: # Docker is not supported on macOS and Windows.
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [macOS-latest, windows-latest]
  #       ros_distribution:
  #         - galactic
  #   steps:
  #     - uses: ros-tooling/setup-ros@v0.2
  #       with:
  #         required-ros-distributions: ${{ matrix.ros_distribution }}
  #     - name: build and test
  #       uses: ros-tooling/action-ros-ci@v0.2
  #       with:
  #         package-name: crazyswarm
  #         target-ros2-distro: ${{ matrix.ros_distribution }}

  build_docker: # On Linux, use docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - galactic

        # Define the Docker image(s) associated with each ROS distribution.
        include:
          # Galactic Geochelone (May 2021 - November 2022)
          - docker_image: ubuntu:focal
            ros_distribution: galactic

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      # There is a bug in vcstools, where submodules are not pulled recursively
      # See https://github.com/dirk-thomas/vcstool/issues/205
      # This is fixed in master, but not in the latest release
      # Pull the latest version here
      - name: install vcstool
        run: |
          sudo apt -y remove python3-vcstool
          sudo pip3 install git+https://github.com/dirk-thomas/vcstool.git@7d1329f296cef4b767bf7ba0bf53a29dd3d3019c
          vcs --version

      - name: install dependencies via apt
        run: |
          sudo apt update
          sudo apt install -y libusb-1.0-0-dev
          sudo apt install -y freeglut3-dev gnupg graphviz-dev libann-dev libassimp-dev libbullet-dev libeigen3-dev libf2c2-dev libfcl-dev libglew-dev libglfw3-dev libjsoncpp-dev liblapack-dev libopencv-dev libpng-dev libqhull-dev libx11-dev

      - name: force git to use https rather than ssh
        run: |
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "git://"

      - uses: actions/checkout@v2
      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: uav-rai-demo
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: rosinstall
          extra-cmake-args: -DCMAKE_BUILD_TYPE=Release -DMARC_BUILD=OFF